services:
  server:
    build: .
    environment:
      - TES3MP_SERVER_GENERAL_HOSTNAME="Containerized TES3MP Server"
    volumes:
      - "./data:/server/data"
      - "./config:/server/config"
    ports:
      - "25565:25565/udp"
